### ISSUE TITLE
Inconvenient to `Maker.file` for an existing file

### ISSUE THREAD

**Issue by panlanfeng** [tshort/Maker.jl#20]
Thanks for this great packages. I just started to try it and I have a question here.

Not sure if I am using it the right way but it does not make sense to have to do `Maker.file("somefile")` for files that contains code or data. Why not just check them in the folder instead of "making" them as if they are some kind of output?

Here is my make file. Each pdf file depends on a "csv" and a "jl" file. Are there any specific reason to do those `Make.file` with no dependencies?

```
using Maker
Maker.file("./figures2/teststat22.pdf", ["teststat22.csv", "teststat22.jl"]) do
    include("teststat22.jl") #this file reads the csv and does the plotting
end
Maker.file("./figures2/teststat33.pdf", ["teststat33.csv", "teststat33.jl"]) do
    include("teststat33.jl")
end
Maker.file("./figures2/teststat12.pdf", ["teststat12.csv", "teststat12.jl"]) do
    include("teststat12.jl")
end

#why I have to do this? They are already in the folder.
Maker.file("teststat22.csv")
Maker.file("teststat33.csv")
Maker.file("teststat22.jl")
Maker.file("teststat33.jl")

Maker.task("default", ["./figures2/teststat22.pdf", "./figures2/teststat33.pdf"])

make()
```

**Comment by tshort** [comment]
Good input, @panlanfeng. The `Maker.file("teststat22.csv")` line registers that name as a file task. Without that, Maker doesn't know that "teststat22.csv" is a file task. It could be a directory, a variable, or generic task. The simplest way to handle this now is to register them in one swoop. Here's an example:

``` julia
using Glob
map(Maker.file, glob("teststat*.*"))
```

We might be able to provide a shortcut that registers dependencies automatically and provides more features:

``` julia
Maker.file("./figures2/teststat22.pdf", FileList(["teststat22.csv", "teststat22.jl"])) do
    include("teststat22.jl") #this file reads the csv and does the plotting
end
```

or maybe with wildcards:

``` julia
Maker.file("./figures2/teststat22.pdf", FileList("teststat22.*")) do
    include("teststat22.jl") #this file reads the csv and does the plotting
end
```

Ruby's Rake has [a feature](http://devblog.avdi.org/2014/04/22/rake-part-2-file-lists/) like this. This feature has been filed for Maker (#4), but it's not on the top of my priority list. 

If a `FileList` did the file look-ups upon definition, this would be easy to implement. If it does them on the fly, it's harder to implement. Doing it on the fly is probably the most desirable option.

As you are hinting at, it may work to assume that all undefined dependencies are file targets. That bothers me because misspellings might lead to subtle bugs. Then, some action you expect to happen may not run. If you have to register everything, then a misspelling is more likely to cause an error rather than a subtle bug.

Please jump in if you have other suggestions on ways to make this more obvious or easier.

**Comment by tshort** [comment]
I rethought this one last night. I'm willing to give it a try. See PR #21.

**Comment by tshort** [comment]
This is merged. It's not in a tagged release, so you'll have to use `Pkg.checkout`. I'll close this issue now. If you run into problems, reopen this, or open a new issue.

**Comment by panlanfeng** [comment]
Thanks for the change. It works well. Hope this package become even better.
